"""Top-level index.html aggregator for all SMA HTML reports.

Scans `out_dir` for known module HTML reports (dedicated_pools, serverless_pools,
spark_pools, pipelines, monitoring, fabric_mapping) and writes an `index.html`
landing page with cards linking to each one. Missing reports are listed as
"not generated yet" with the exact `sma analyze-...` command to produce them.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, select_autoescape

from .html_common import SHARED_CSS

# (display title, file-stem, sma command, short description)
_MODULES: list[tuple[str, str, str, str]] = [
    ("Dedicated SQL Pools", "dedicated_pools", "sma analyze-dedicated-pools",
     "Schemas, tables, columns, distribution candidates, statistics, T-SQL surface gaps."),
    ("Serverless SQL", "serverless_pools", "sma analyze-serverless-pools",
     "Databases, external data sources & tables, top queries, daily usage, cost estimate."),
    ("Apache Spark Pools", "spark_pools", "sma analyze-spark-pools",
     "Pools, notebooks, lint findings, runtime mapping, libraries, job runs."),
    ("Pipelines", "pipelines", "sma analyze-pipelines",
     "Pipelines, activities, linked services, datasets, triggers, integration runtimes."),
    ("Monitoring", "monitoring", "sma analyze-monitoring",
     "Azure Monitor metrics for dedicated pools (DWU, queries, connections), DWU days, KQL."),
    ("Storage (ADLS + pool size)", "storage", "sma analyze-storage",
     "Storage account inventory (ADLS Gen2 flag), capacity (UsedCapacity / BlobCapacity), dedicated SQL pool size in MB / GB."),
    ("Fabric Migration Plan", "fabric_mapping", "sma map-to-fabric",
     "Readiness score, capacity projection, recommendations, migration runbook."),
    ("Governance (mid-term)", "governance", "sma analyze-governance",
     "RBAC, managed private endpoints, customer-managed keys, Purview lineage."),
    ("Security (mid-term)", "security", "sma analyze-security",
     "Firewall rules, AAD-only, TLS, encryption, credentials inventory, findings."),
    ("Cost (mid-term)", "cost", "sma analyze-cost",
     "Month-over-month consumption from Cost Management + Fabric capacity comparison."),
    ("Fabric validation (mid-term)", "fabric_validation", "sma validate-fabric",
     "Post-migration object/row/collation/T-SQL surface checks vs the source inventory."),
    ("Run delta (mid-term)", "run_delta", "sma analyze-all",
     "Side-by-side diff of artifact hashes / record counts vs the previous run."),
]

_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Unified Solution Migration Analyzer &mdash; Index</title>
<style>{{ css }}
.spa-banner { background: #eef6ff; border: 1px solid #b6d6ff; border-radius: 6px;
              padding: 12px 16px; margin: 16px 0; display: flex; align-items: center;
              justify-content: space-between; gap: 12px; }
.spa-banner .copy { flex: 1; }
.spa-banner h3 { margin: 0 0 4px 0; }
.spa-banner p  { margin: 0; }
.spa-banner .btn { white-space: nowrap; }
</style></head><body>
<h1>Unified Solution Migration Analyzer &mdash; Reports</h1>
<div class="meta">
 <div><strong>Output directory:</strong> <code>{{ out_dir }}</code></div>
 <div><strong>Generated:</strong> {{ generated_at }}</div>
 <div><strong>Available reports:</strong> {{ available_count }} of {{ total }}</div>
</div>

{% if spa_present %}
<div class="spa-banner">
 <div class="copy">
  <h3>Interactive web UI available</h3>
  <p>The static SPA is installed in <code>./webui/</code>. It cross-links readiness, code-objects, recommendations, runbook, and run-delta into one filterable view.</p>
 </div>
 <a class="btn" href="webui/index.html">Open web UI &rarr;</a>
</div>
{% endif %}

<h2>Modules</h2>
<div class="card-grid">
{% for m in modules %}
 <div class="card">
  <h3>{{ m.title }}{% if not m.available %} <span class="pill warn">missing</span>{% else %} <span class="pill ok">ready</span>{% endif %}</h3>
  <p>{{ m.description }}</p>
  {% if m.available %}
   <p class="small muted">
    <a href="{{ m.html_name }}" class="btn">Open HTML &rarr;</a>
    {% for sib in m.siblings %} &middot; <a href="{{ sib.name }}">{{ sib.label }}</a>{% endfor %}
   </p>
  {% else %}
   <p class="small muted">Run <code>{{ m.command }}</code> with <code>-f html</code> to generate.</p>
  {% endif %}
 </div>
{% endfor %}
</div>

<div class="footer">Generated by Unified Solution Migration Analyzer.</div>
</body></html>
"""


def _siblings_for(stem: str, out_dir: Path) -> list[dict[str, str]]:
    """Return links to sibling artifacts (json / md) so the card surfaces them."""
    out: list[dict[str, str]] = []
    candidates = [
        (f"{stem}.json", "JSON"),
        (f"{stem}.md", "Markdown"),
    ]
    for name, label in candidates:
        if (out_dir / name).exists():
            out.append({"name": name, "label": label})
    return out


def write_index(out_dir: Path) -> Path:
    """Build `out_dir/index.html` with a card per module."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    available = 0
    for title, stem, command, desc in _MODULES:
        html_name = f"{stem}.html"
        html_path = out_dir / html_name
        is_available = html_path.exists()
        if is_available:
            available += 1
        rows.append({
            "title": title,
            "description": desc,
            "command": command,
            "html_name": html_name,
            "available": is_available,
            "siblings": _siblings_for(stem, out_dir) if is_available else [],
        })

    env = Environment(autoescape=select_autoescape(["html", "xml"]))
    template = env.from_string(_TEMPLATE)
    html = template.render(
        css=SHARED_CSS,
        out_dir=str(out_dir),
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        modules=rows,
        available_count=available,
        total=len(_MODULES),
        spa_present=(out_dir / "webui" / "index.html").exists(),
    )
    path = out_dir / "index.html"
    path.write_text(html, encoding="utf-8")
    return path
