"""HTML report writer for the monitoring module."""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from jinja2 import Environment, select_autoescape

from ...reporting.html_common import SHARED_CSS, SHARED_FILTER_JS
from .models import MonitoringAnalysis

_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Unified Solution Migration Analyzer &mdash; Monitoring</title>
<style>{{ css }}</style></head><body>
<h1>Unified Solution Migration Analyzer &mdash; Monitoring</h1>
<div class="meta">
 <div><strong>Workspace:</strong> {{ r.workspace_name }}</div>
 <div><strong>Window:</strong> <code>{{ r.window_start.isoformat() }}</code> &rarr;
   <code>{{ r.window_end.isoformat() }}</code> ({{ r.interval }})</div>
 <div><strong>Generated:</strong> {{ r.generated_at.isoformat() }}</div>
</div>

<div class="grid-2">
 <div class="stat"><div class="label">Series</div><div class="value">{{ r.series|length }}</div></div>
 <div class="stat"><div class="label">Resources</div><div class="value">{{ extras.resources|length }}</div></div>
 <div class="stat"><div class="label">DWU days</div><div class="value">{{ r.dwu_days|length }}</div></div>
 <div class="stat"><div class="label">Log Analytics queries</div><div class="value">{{ r.log_analytics|length }}</div></div>
</div>

<div class="toc">
 <strong>Sections:</strong>
 {% if r.series %}<a href="#summary">Metric summary</a> <a href="#series">Series detail</a>{% endif %}
 {% if r.dwu_days %}<a href="#dwu">DWU days</a>{% endif %}
 {% if r.log_analytics %}<a href="#kql">Log Analytics</a>{% endif %}
 {% if r.errors %}<a href="#errors">Errors</a>{% endif %}
</div>

{% if r.errors %}
<h2 id="errors">Collection errors</h2>
<details open><summary class="err">{{ r.errors|length }} error(s)</summary>
 <ul class="err">{% for e in r.errors %}<li>{{ e }}</li>{% endfor %}</ul></details>
{% endif %}

{% if r.series %}
<h2 id="summary">Metric summary</h2>
<input class="filter" type="text" placeholder="Filter metrics" oninput="smaFilter(this,'tbl-sum')"/>
<table id="tbl-sum">
 <tr><th>Resource</th><th>Metric</th><th>Aggregation</th><th>Unit</th>
  <th class="num">Min</th><th class="num">Avg</th><th class="num">P95</th><th class="num">Max</th><th class="num">Points</th></tr>
 {% for s in extras.sorted_series %}
 <tr>
  <td><code>{{ s.resource_name }}</code><br><span class="small muted">{{ s.resource_kind }}</span></td>
  <td>{{ s.metric_name }}</td>
  <td>{{ s.aggregation }}</td>
  <td>{{ s.unit or '' }}</td>
  <td class="num">{{ fmt(s.min_value) }}</td>
  <td class="num">{{ fmt(s.avg_value) }}</td>
  <td class="num">{{ fmt(s.p95_value) }}</td>
  <td class="num">{{ fmt(s.max_value) }}</td>
  <td class="num">{{ s.points|length }}</td>
 </tr>
 {% endfor %}
</table>

<h2 id="series">Series detail (drill-down)</h2>
{% for resource_name, group in extras.series_by_resource.items() %}
<details><summary><code>{{ resource_name }}</code> &mdash; {{ group|length }} series</summary>
 {% for s in group %}
 <details><summary>{{ s.metric_name }} <span class="small muted">({{ s.aggregation }}, {{ s.points|length }} points)</span></summary>
  <table>
   <tr><th>Timestamp</th><th class="num">Value</th></tr>
   {% for ts, v in s.points %}
   <tr><td class="nowrap small">{{ ts.isoformat() if ts else '' }}</td><td class="num">{{ fmt(v) }}</td></tr>
   {% endfor %}
  </table>
 </details>
 {% endfor %}
</details>
{% endfor %}
{% endif %}

{% if r.dwu_days %}
<h2 id="dwu">DWU days</h2>
<input class="filter" type="text" placeholder="Filter DWU days" oninput="smaFilter(this,'tbl-dwu')"/>
<table id="tbl-dwu">
 <tr><th>Pool</th><th>Day</th><th class="num">Active hours</th><th class="num">Active DWU-h</th>
  <th class="num">Peak DWU</th><th class="num">Peak %</th></tr>
 {% for d in r.dwu_days %}
 <tr><td><code>{{ d.pool_name }}</code></td><td class="nowrap small">{{ d.day }}</td>
  <td class="num">{{ '%.2f'|format(d.active_hours) }}</td>
  <td class="num">{{ '%.2f'|format(d.active_dwu_hours) }}</td>
  <td class="num">{{ '%.0f'|format(d.peak_dwu) }}</td>
  <td class="num">{{ '%.0f'|format(d.peak_pct) }}%</td></tr>
 {% endfor %}
</table>
{% endif %}

{% if r.log_analytics %}
<h2 id="kql">Log Analytics queries</h2>
{% for q in r.log_analytics %}
<details>
 <summary><code>{{ q.query_name }}</code> &mdash; {{ q.rows|length }} row(s){% if q.error %} <span class="pill err">error</span>{% endif %}</summary>
 {% if q.error %}<p class="err">{{ q.error }}</p>{% endif %}
 {% if q.rows %}
 <table>
  <tr>{% for k in q.rows[0].keys() %}<th>{{ k }}</th>{% endfor %}</tr>
  {% for row in q.rows %}<tr>{% for v in row.values() %}<td class="small">{{ v }}</td>{% endfor %}</tr>{% endfor %}
 </table>
 {% endif %}
</details>
{% endfor %}
{% endif %}

<div class="footer">Generated by Unified Solution Migration Analyzer.</div>
<script>{{ js }}</script>
</body></html>
"""


def _fmt(value: float | None) -> str:
    if value is None:
        return ""
    if abs(value) >= 1000:
        return f"{value:.0f}"
    return f"{value:.2f}"


def _build_extras(result: MonitoringAnalysis) -> dict[str, Any]:
    by_resource: dict[str, list[Any]] = defaultdict(list)
    for s in result.series:
        by_resource[s.resource_name].append(s)
    for v in by_resource.values():
        v.sort(key=lambda s: s.metric_name)
    sorted_series = sorted(result.series, key=lambda s: (s.resource_name, s.metric_name))
    return {
        "series_by_resource": dict(by_resource),
        "sorted_series": sorted_series,
        "resources": list(by_resource.keys()),
    }


def write_html(result: MonitoringAnalysis, out_dir: Path) -> Path:
    env = Environment(autoescape=select_autoescape(["html", "xml"]))
    template = env.from_string(_TEMPLATE)
    html = template.render(r=result, extras=_build_extras(result),
                           fmt=_fmt, css=SHARED_CSS, js=SHARED_FILTER_JS)
    path = out_dir / "monitoring.html"
    path.write_text(html, encoding="utf-8")
    return path
